apiVersion: v1
kind: Secret
metadata:
    name: vsphere-config-secret
    namespace: vmware-system-csi
stringData:
    csi-vsphere.conf: ENC[AES256_GCM,data:qDPEYA3GrYqrUO2feZi3twRUbqsCTm/UrECBLDigbNcO82OSeagqCVfasK1NizZ+VI7IanKW/CJM0xfMZwJQ5WNr1HaR4jX6Yi/XsMCK8bkLkivq33n4BLSbWYUE6gi4Eq25i1Pj3LvKL3psJnrvA8qbH15OiXEA996FqASeakMt1t6nYrsI1NNJQ9xco1ZQffRCkIgk912XjekQnBSdLJMtZMm58VxwuMS24OWJZHAmbbQ0D/8ECziLi/5CTeIz9Z0DhDFEKi5Lqe93hEYf3+eItF/U1AM5sZpjRXeU8mtxDHmMlQFw6SD+FxEltsnp6247VkUQh8O5+mUVqnnMwC737G8RDRLHK/5T1/giAB8r7tC2mCiCzw==,iv:WJ2/AmlKNelOltMzCSJP2QOgOU8s6GRxddhdSF5R5sQ=,tag:QQ0kp+2WXGzw/DDsQd3zJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-20T22:57:17Z"
    mac: ENC[AES256_GCM,data:9OBfLrHff8K3Hi2WXREkdXJ/f+Gg16FUBVIwA84RdS0fmKaFRirhaEVUmPSbmGp8F9/QNgumtqZ/eCMkQGIusSviSxigBhyJGyOmCwYFYoAulm1O9b7+P4jq0X2VHVyDshr/gLdS+NG0x+gMFd8/LAK9kIj44XhDXTN2CPldSW4=,iv:zn7R7vomqfTlpF91oRzmDhbXjNu/h16e4OvGgBQT0nA=,tag:hcmK64KSeIqpYt0DMRIBuQ==,type:str]
    pgp:
        - created_at: "2022-12-20T15:59:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9VhhrDDnyi5AQ//S2jbLVbrnq2oyrwa8ge3KlWLt+DgQEAJ1gTnn1hBAQtM
            puqFhaHJ/rHdHJ3I5W+fwE5qWhMJ6vu2j+kUXn+QlE3t2YOpRqmJnoTCFkev7R2F
            hQjBaGgZNCMavAu3zxUItKHL+PBzjR/9ZLUv1De8b5Ymi8Xx77j7C92COt1D9aSx
            LpOd/JjNdg+MQMYbcSCLWkn3TSJ6nL4PuPDyY70kiceFCclDoXnO6bQWKI1Jx4/P
            OFgltZZUIMfe2MnNziI6FPe7k9obWlFwUL5hAdibnmFo3miJmCnNKzrBcOh34rax
            68J6pJ3dfrV93qEARByi39xJ2qOLj5hTkVnQaF5BXuOKE+Sczw4+t4JjHAnQdQEu
            h4rS5/gVH6XZee0s1uO4nHhyZ6kCzwu5juOMDoMvH4x2t/1/fYkl13Mt4U1vZNNa
            aojXqlj/XHIq7NZNPo7WxCioATIT4ZFmzDTShqChhuxEbR9tb0yB/odgUMCeEWiw
            h7Vd+QbjUyjhw9jQB3iYmhiYth7uyba06X5TYgsqYgHG8+6T3IYxAw2I4ezmHL+C
            nUEHAcc6JcLZLT4DK5ssPtgIlttiAEOahaHZPN3aLedRIN1Eugun07XtsjxuLKLK
            WbZbLh2uC+/lV4L/nJYjWCwzNLEe6fslVnGFN09/wAWFgGHwuKZq3lGmhOkYN1zS
            XgGhrAEGYfdpRQQ7jA/UtFepFZ5gVRqeUJvCHWa3aMcFKdsyhANphn2A1ErAJfRj
            AKYe+u5eZVZJmtYSPYJBWaxacdKNgWsnOoCdicYb7j+FoyDZG5cR9bwAuJZeNnc=
            =dxXV
            -----END PGP MESSAGE-----
          fp: FAC1CF820538F4A07C8F4657DAD5DC6A21303194
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
