apiVersion: v1
data:
    csi-vsphere.conf: ENC[AES256_GCM,data:4diYr97/8CpklpuANQbO/6o/ONSQ5Dy79VFR10sRypBJ+QQ1Luy1rIkdaIeoP/Qwo/383kLBaswa7CYRZ+VMxCF5kJ11ZAtHN9Fg/BIyD99ZwP6AAUfC+7nnhcJ6W1shhKzzrdYxaYKJieO1lbBgfuYAtIjmr2uKVKvs8l99lNW9Cm4vCWtQPR6BBBeLHdBrzTLPN+iYwtLucXsJJlJvsV2xfMANDn7RHaj+W+az9192beYo6Y8ek5VEpC/HReZWpN1Dh0+8P//b+KYkHwSF296m1CpR8fi6R4wcLlVGpW9rZwZLWkBoKuR0j0AWE42scz49uvQyKWqz8NtPjJr+ptzJUl9vJ/vGe+iABgFBhT9F+roRUVhMNaL/z5IJN53eNZunIpKgB2VMx4khinoOJfLa3sfTgpy6uPtHkIEUTrPPHHGu5oKiNNx4ZaLinxLVrJmLJ33qUeX5uwzwU3MB1+sdhdhkUXD8eKH0n1PaKgzXhLUIDqaugQ==,iv:6fWHriwg23BWOpRdnKwGkGKW4V8erJvX+XOlQWsZgTk=,tag:rHHdNRCBJXfxYxQgROLLGw==,type:str]
kind: Secret
metadata:
    name: vsphere-config-secret
    namespace: vmware-system-csi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-20T16:01:11Z"
    mac: ENC[AES256_GCM,data:z/OBwZ/ln1U1WxzJ4UFfUgaKOEZERhb8O0FlB5jz/9PNNa0NCioyj8aSdI3x3ERiqoWBhHvzy29+AAGQynC4/R8JeD4eCe28A6F1Um3GvoZGEddJPvNRkWxZ/25DX6HGPeW0SRiea7ytk8Oc2zFsEE4n9YbBQiDVwI6MLKRjwPE=,iv:s2zwB3sZgzCVVSnFevlzOtZxtP33Qzy4ny8WXn6Mib0=,tag:bxCfdpCJ7b7l2lVhKRrqLg==,type:str]
    pgp:
        - created_at: "2022-12-20T15:59:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9VhhrDDnyi5AQ//S2jbLVbrnq2oyrwa8ge3KlWLt+DgQEAJ1gTnn1hBAQtM
            puqFhaHJ/rHdHJ3I5W+fwE5qWhMJ6vu2j+kUXn+QlE3t2YOpRqmJnoTCFkev7R2F
            hQjBaGgZNCMavAu3zxUItKHL+PBzjR/9ZLUv1De8b5Ymi8Xx77j7C92COt1D9aSx
            LpOd/JjNdg+MQMYbcSCLWkn3TSJ6nL4PuPDyY70kiceFCclDoXnO6bQWKI1Jx4/P
            OFgltZZUIMfe2MnNziI6FPe7k9obWlFwUL5hAdibnmFo3miJmCnNKzrBcOh34rax
            68J6pJ3dfrV93qEARByi39xJ2qOLj5hTkVnQaF5BXuOKE+Sczw4+t4JjHAnQdQEu
            h4rS5/gVH6XZee0s1uO4nHhyZ6kCzwu5juOMDoMvH4x2t/1/fYkl13Mt4U1vZNNa
            aojXqlj/XHIq7NZNPo7WxCioATIT4ZFmzDTShqChhuxEbR9tb0yB/odgUMCeEWiw
            h7Vd+QbjUyjhw9jQB3iYmhiYth7uyba06X5TYgsqYgHG8+6T3IYxAw2I4ezmHL+C
            nUEHAcc6JcLZLT4DK5ssPtgIlttiAEOahaHZPN3aLedRIN1Eugun07XtsjxuLKLK
            WbZbLh2uC+/lV4L/nJYjWCwzNLEe6fslVnGFN09/wAWFgGHwuKZq3lGmhOkYN1zS
            XgGhrAEGYfdpRQQ7jA/UtFepFZ5gVRqeUJvCHWa3aMcFKdsyhANphn2A1ErAJfRj
            AKYe+u5eZVZJmtYSPYJBWaxacdKNgWsnOoCdicYb7j+FoyDZG5cR9bwAuJZeNnc=
            =dxXV
            -----END PGP MESSAGE-----
          fp: FAC1CF820538F4A07C8F4657DAD5DC6A21303194
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
