---
# Source: fluent-bit/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "fluent-bit-test-connection"
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: "2.0.5"
  annotations:
    "helm.sh/hook": test-success
  namespace: logging-system
spec:
  containers:
    - name: wget
      image: "busybox:latest"
      imagePullPolicy: Always
      command: ['wget']
      args: ['fluent-bit:2020']
  restartPolicy: Never
